[project]
name = "stylevec"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.26",
    "scikit-learn>=1.8",
    "requests",
    "huggingface-hub",
    "transformers",
    "torch",
    "accelerate",
    "peft>=0.10",
    "modelscope>=1.34.0",
    "psutil>=7.2.2",
    "matplotlib>=3.10.8",
    "ollama>=0.6.1",
    "pyarrow>=23.0.1",
    "pandas>=3.0.2",
    "litellm>=1.83.4",
    "datasets>=4.8.4",
    "zstandard>=0.25.0",
    "cloudscraper>=1.2.71",
    "bs4>=0.0.2",
    "lxml>=6.1.0",
    "undetected-chromedriver>=3.5.5",
    "beautifulsoup4>=4.14.3",
    "markdownify>=1.2.2",
    "fake-useragent>=2.2.0",
    "sentence-transformers>=5.4.1",
    "tensorboard>=2.20.0",
    "umap-learn>=0.5.12",
    "opentsne>=1.0.4",
    "ebooklib>=0.18",
    "mobi>=0.3.3",
]
